# Generated by Django 4.2.30 on 2026-04-20 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0001_initial"),
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("run_name", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_cash",
                    models.DecimalField(
                        decimal_places=2, default=100000, max_digits=18
                    ),
                ),
                ("benchmark_symbol", models.CharField(blank=True, max_length=16)),
                ("universe_symbols", models.JSONField(blank=True, default=list)),
                ("run_parameters", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "engine_version",
                    models.CharField(default="phase2-v1", max_length=32),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_runs",
                        to="access.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backtest_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_runs",
                        to="strategies.strategyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestTrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=16)),
                ("side", models.CharField(default="long", max_length=8)),
                ("entry_date", models.DateField()),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("entry_price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "gross_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "net_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "return_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("exit_reason", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["entry_date", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="BacktestMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_type", models.CharField(default="summary", max_length=64)),
                ("label", models.CharField(max_length=128)),
                ("value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["metric_type", "label"],
            },
        ),
        migrations.CreateModel(
            name="BacktestArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artifact_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["artifact_type"],
            },
        ),
    ]
